<?php

use Drupal\Component\Utility\Unicode;
use Drupal\Core\Block\BlockPluginInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Form\FormStateInterface;



function poc_form_alter(&$form, FormStateInterface $form_state, $form_id) {
	
	//echo '<pre>';
	//print_r($form);

   if ($form_id == 'node_ad_campaign_form' || $form_id == 'node_ad_campaign_edit_form') {
	   
	   //echo '<pre>';
	   //$form['field_type_of_ad']['widget'][0]['target_id']['#type']='select';
	} 
}


?>